"""Export and import .env file functionality for envault."""

from pathlib import Path
from typing import Optional


def parse_dotenv(content: str) -> dict[str, str]:
    """Parse a .env file content into a dictionary."""
    result = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip surrounding quotes if present
        if len(value) >= 2 and value[0] in ('"', "'") and value[-1] == value[0]:
            value = value[1:-1]
        if key:
            result[key] = value
    return result


def render_dotenv(secrets: dict[str, str], comment: Optional[str] = None) -> str:
    """Render a dictionary of secrets as .env file content."""
    lines = []
    if comment:
        lines.append(f"# {comment}")
        lines.append("")
    for key, value in sorted(secrets.items()):
        # Quote values that contain spaces or special characters
        if any(c in value for c in (" ", "#", "'", '"', "\n")):
            escaped = value.replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n" if lines else ""


def export_to_file(secrets: dict[str, str], path: Path, overwrite: bool = False) -> None:
    """Write secrets to a .env file on disk."""
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists. Use overwrite=True to replace it.")
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_dotenv(secrets, comment="Generated by envault")
    path.write_text(content, encoding="utf-8")


def import_from_file(path: Path) -> dict[str, str]:
    """Read and parse a .env file from disk."""
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist.")
    content = path.read_text(encoding="utf-8")
    return parse_dotenv(content)
